### ISSUE TITLE
More sample 

### ISSUE THREAD

**Issue by mori3848** [vishwas-r/WP-CanvasJS-Charts#2]
hi
Thank you for your best solution to create chart by canvasJs.
can you give us some more example shortcode for another type of chart like doughnut.

**Comment by vishwas-r** [comment]
You can create doughnut chart as shown below.

> [canvasjschart options="{'theme':'dark2','exportFileName':'Doughnut Chart','exportEnabled':true,'animationEnabled':true,'title':{'text':'Monthly Expense'},'data':new Array({'type':'doughnut','innerRadius':90,'showInLegend':true,'toolTipContent':'<b>{name}</b>: ${y} (#percent%)','indexLabel':'{name} - #percent%','dataPoints':new Array({'y':450,'name':'Food'},{'y':120,'name':'Insurance'},{'y':300,'name':'Travelling'},{'y':800,'name':'Housing'},{'y':150,'name':'Education'},{'y':150,'name':'Shopping'},{'y':250,'name':'Others'})})}"]

**Or**
Simply store entire options as a JSON file & pass the file url as optionsurl as shown below.

> [canvasjschart optionsurl="https://api.npoint.io/386582c81676a59633b9"]

The above 2 shortcodes will generate a chart as shown below.
![Doughnut Chart](https://i.imgur.com/JhJq4nS.png)

**Comment by mori3848** [comment]
Thank you.
Please set a sample shortcode for each chart type.
I worked with the plugin for several hours and I could not make another chart except for the ones you gave as an example.

**Comment by mori3848** [comment]
Hi
please check it on WordPress and with other elements.
After rendering, the diagram is not placed in the right place and comes on top of other texts. Changing the CSS does not solve the problem.
