### ISSUE TITLE
Diagram is not placed in the right place

### ISSUE THREAD

**Issue by mori3848** [vishwas-r/WP-CanvasJS-Charts#4]
Hi
please check it on WordPress and with other elements.
After rendering, the diagram is not placed in the right place and comes on top of other texts. Changing the CSS does not solve the problem.

**Comment by vishwas-r** [comment]
[Setting height](https://github.com/vishwas-r/WP-CanvasJS?tab=readme-ov-file#styling-chart-container) of the chart seems to work properly in this case. Here is an example short-code
`[canvasjschart options="{title:{text: 'CanvasJS Column Chart'}, data: new Array({dataPoints: new Array({ label: 'apple', y: 10 },{ label: 'orange', y: 15 },{ label: 'banana', y: 25 },{ label: 'mango', y: 30 },{ label: 'grape', y: 28 })})}" style="width:100%;height:360px"]`

**Comment by mori3848** [comment]
thank you. it is very good.
