### ISSUE TITLE
radar and  Stacked Bar Charts

### ISSUE THREAD

**Issue by mori3848** [vishwas-r/WP-CanvasJS-Charts#5]
Hi, 
How can I create **radar** and **stacked bar charts** using this plugin?

**Comment by vishwas-r** [comment]
Check out [CanvasJS official documentation](https://canvasjs.com/docs/charts/chart-types/) for list of supported chart-types & customization options available in the library. As of now, radar chart is not supported by CanvasJS, as per documentation.

**Closing this as it's not an issue.**

**Comment by mori3848** [comment]
Can you give me shortcode for Stacked Bar Charts and other kind of chart.

**Comment by vishwas-r** [comment]
`[canvasjschart options="{title:{text: 'CanvasJS Column Chart'}, data: new Array({type: 'stackedBar',dataPoints: new Array({ label: 'apple', y: 10 },{ label: 'orange', y: 15 },{ label: 'banana', y: 25 },{ label: 'mango', y: 30 },{ label: 'grape', y: 28 })},{type: 'stackedBar',dataPoints: new Array({ label: 'apple', y: 10 },{ label: 'orange', y: 15 },{ label: 'banana', y: 25 },{ label: 'mango', y: 30 },{ label: 'grape', y: 28 })})}" style="width:100%;height:360px"]`

Checkout https://github.com/vishwas-r/WP-CanvasJS/wiki/Chart-Types#5-stacked-bar-chart

Updating the JSON that you pass as option will let you change chart-types & other options. You can even store the entire JSON as a file & pass URL of that file as option as shown below.
`[canvasjschart optionsUrl="https://api.npoint.io/5448b28da1502b036561" style="width:100%;height:360px"]`
