### ISSUE TITLE
NEW issue

### ISSUE THREAD

**Issue by mori3848** [vishwas-r/WP-CanvasJS-Charts#6]
Thank you.
This code from https://github.com/vishwas-r/WP-CanvasJS/wiki/Chart-Types#5-stacked-bar-chart
not work properly.
8. Candlestick Chart:
[canvasjschart options="{title:{text: 'CanvasJS Candlestick Chart'}, data: new Array({type: 'candlestick', dataPoints: new Array({ x: 10, y: [20, 30, 10, 15] },{ x: 20, y: [30, 40, 20, 35] },{ x: 30, y: [35, 45, 25, 40] },{ x: 40, y: [45, 50, 30, 40] },{ x: 50, y: [40, 60, 35, 55] })})}"]

**Comment by vishwas-r** [comment]
Updated example
